/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package femail_pms;

import static femail_pms.ParkingDatabase.setConnection;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
import java.util.Date;  
import javax.swing.JComboBox;


/**
 *
 * @author SYED ALI ABBAS
 */
public class ParkingPlots extends javax.swing.JFrame {

    /**
     * Creates new form ParkingPlots
     */
    public ParkingPlots() {
        initComponents();
      
        Connection con1 = setConnection();
try{
               Statement st2 = con1.createStatement();
               ResultSet rs2 = st2.executeQuery("SELECT * FROM FLOOR");
               
               while(rs2.next())
               { 
                  jComboBox1.addItem(rs2.getString("floor_level"));
             
               }
              
               
               rs2.close();
               st2.close();
               con1.close();
           }
           catch(Exception e)
           {
               System.out.println("Error Occurs");
           }
//        ------------------------------------------------------------------------
           Connection con = setConnection();
           try{
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM PARKING_TYPE_TABLE");
//               System.out.println("Select Quer work");
//               System.out.println(rs);
               while(rs.next())
               { 
                  parkingtypedd.addItem(rs.getString("parking_type_name"));
               }
               
               rs.close();
               st.close();
               con.close();
           }
           catch(Exception e)
           {
               System.out.println("Error Occurs");
           }
//           -------------------------------------------------

        
    }
ParkingDatabase parkingdb;
    JFrame f;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parkingtypedd = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parkingtypedd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        parkingtypedd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vehicle Type" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Vehicle Name Plate");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Save Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Floor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Plots" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Slot", "Slot-A", "Slot-B", "Slot-C", "Slot-D", "Slot-E", "Slot-F", "Slot-G", "Slot-H", "Slot-I", "Slot-J" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Price");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book parking now");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(parkingtypedd, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(219, 219, 219))
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(parkingtypedd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
//                      parkingdb = new ParkingDatabase();
//                      Date date = new Date();
//                      int parking_id=0;
//                      Connection con = setConnection();
//                     
//           try{
//               Statement st = con.createStatement();
//               ResultSet rs = st.executeQuery("SELECT parking_id FROM parking_type_table where parking_type_name='"+parkingtypedd.getSelectedItem()+"'");
//                while(rs.next())
//               {
//               parking_id = rs.getInt("parking_id");
//               }
//               rs.close();
//               st.close();
//               con.close();
//           }
//           catch(Exception e)
//           {
//               System.out.println("Error Occurs at parkingn type");
//           }
                      
    String query="INSERT into parkingInformation(floor_level,plot_name,slot_name,vehicle_name_plate,entrydate,entry_time,parkingtype,price)VALUES('"+jComboBox1.getSelectedItem()+"','"+jComboBox2.getSelectedItem()+"','"+jComboBox3.getSelectedItem()+"','"+jTextField2.getText()+"','"+java.time.LocalDate.now()+"','"+java.time.LocalTime.now().toString()+"','"+jTextField2.getText()+"','"+jTextField1.getText()+"')";
    parkingdb.DataInsert(query);
    JOptionPane.showMessageDialog(f,"Record Inserted Successfully","Alert",JOptionPane.WARNING_MESSAGE);
                  
//prarking_plot_id number GENERATED ALWAYS AS IDENTITY,
//--  Plot_slot_number varchar2(50),
//--  vehicle_name_plate varchar(50),
//--  entery_date date,
//--  entry_time varchar(50),
//--  exit_time varchar(50),
//-
//--  parking_id number not null,
                
                    
              
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    
 
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
        parkingdb = new ParkingDatabase();
                   jComboBox2.removeAllItems();
                      int floor_id=0;
                      Connection con = setConnection();
                     
           try{
               Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("SELECT floor_id FROM Floor where floor_level='"+jComboBox1.getSelectedItem()+"'");
                while(rs.next())
               {
               floor_id = rs.getInt("floor_id");
               }
//                System.out.println(floor_id);
               rs.close();
               st.close();
               con.close();
           }
           catch(Exception e)
           {
               System.out.println("Error Occurs at parkingn type");
           }
                
           
           
           Connection con1 = setConnection();
try{
               Statement st2 = con1.createStatement();
               ResultSet rs2 = st2.executeQuery("SELECT plot_name FROM plotTable where floor_id="+floor_id+"");
               
               while(rs2.next())
               { 
                  jComboBox2.addItem(rs2.getString("plot_name"));
         
               }
              
               rs2.close();
               st2.close();
               con1.close();
           }
           catch(Exception e)
           {
               System.out.println("Error Occurs");
           }
   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
//                   
//System.out.println("femail_pms.ParkingPlots.jComboBox2ActionPerformed()");
//parkingdb = new ParkingDatabase();
//                      jComboBox3.removeAllItems();
//                      int plot_id=0;
//                      Connection con = setConnection();
//                     
//           try{
//               Statement st = con.createStatement();
//               ResultSet rs = st.executeQuery("SELECT plot_id FROM plotTable where plot_name='"+jComboBox2.getSelectedItem()+"'");
//                while(rs.next())
//               {
//               plot_id = rs.getInt("plot_id");
//               }
//                System.out.println("Combo 3"+ plot_id);
//               rs.close();
//               st.close();
//               con.close();
//           }
//           catch(Exception e)
//           {
//               System.out.println("Error Occurs at parkingn type");
//           }        
//       
//           
//           
//           
//           Connection con1 = setConnection();
//try{
//               Statement st2 = con1.createStatement();
//               ResultSet rs2 = st2.executeQuery("SELECT * FROM slotsTable where plot_id="+plot_id+"");
//               
//               while(rs2.next())
//               { 
//                  jComboBox3.addItem(rs2.getString("slot_name"));
//         
//               }
//              
//               rs2.close();
//               st2.close();
//               con1.close();
//           }
//           catch(Exception e)
//           {
//               System.out.println("Error Occurs");
//           }
//           
//           
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line argument                    
s
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingPlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingPlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingPlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingPlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingPlots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> parkingtypedd;
    // End of variables declaration//GEN-END:variables
}
